export const stats = {
    radius: {
        title: "Diameter",
        stat: [
            "12,756 kilometers",
        ],
    },
    distanceFromSun: {
        title: "Distance from Sun",
        stat: [
            "1.00 astronomical units",
        ],
    },
    mass: {
        title: "Mass",
        stat: [
            "59.8 x 10<sup>23</sup> kg",
        ],
    },
    density: {
        title: "Density",
        stat: [
            "5.5 g / cm<sup>3</sup>",
        ],
    },
    revolution: {
        title: "Revolution Period",
        stat: [
            "1.00 years",
        ],
    }
}

export const geological = {
    volcano: {
        title: 'Volcanoes',
        icon: 'volcano',
        paragraphs: "Earth’s volcanoes have provided various gases that compose our atmosphere such as N<sub>2</sub>, CO<sub>2</sub>, and H<sub>2</sub>O."

    },
    plateTec: {
        title: "Plate Tectonics",
        icon: 'house-crack',
        paragraphs: "<p>Earth’s surface lacks any craters demonstrating the planet’s tectonics. The planet’s geology is a result of plate tectonics.</p> <strong>Results of Plate Tectonics</strong> <ul><li>Continental drift</li><li>Recycling of the ocean floor</li><li>Mountains</li><li>Rift zones</li><li>Subduction zones</li><li>Faults & Earthquakes</li><li>Volcanic eruptions</li></ul>"
    },
    magnet: {
        title: "Magnetic Field",
        icon: 'magnet',
        paragraphs: "Earth’s magnetic field is generated by the planet’s core, and the field extends outside of the planet and into space. The part of the magnetic field located outside Earth’s atmosphere is called the magnetosphere. The magnetosphere protects Earth from the Sun’s harmful solar winds by reflecting them. If these solar winds were not reflected, the planet’s atmosphere would continue to heat up and eventually be destroyed."
    },
}

export const comp = {
    p1: "Since Earth is a terrestrial planet, the composition of Earth consists of iron, silicon, oxygen and other heavier elements.",
}

export const size = {
    p: "Earth is the largest terrestrial planet in the solar system therefore its interior is still molten."
}

export const structure = {
    p: ""
}
export const surface = {
    p: "Earth's most noticeable characteristic is that it is covered in water. This is a result of its surface temperature and location from the Sun. Unlike Venus, whose water and CO<sub>2</sub> are absorbed by the atmosphere, Earth's CO<sub>2</sub> is dissolved in oceans and, in turn, the seafloor rock."
}

export const atmosphere = {
    title: 'Atmosphere composition',
    content: [
        {
            label: 'Nitrogen Gas (N<sub>2</sub>)',
            info: '77%',
        },
        {
            label: 'Oxygen Gas (O<sub>2</sub>)',
            info: '21 %',
        },
        {
            label: 'Argon & Water Vapor (H<sub>2</sub>O) & Carbon Dioxide (CO<sub>2</sub>) & Methane',
            info: '< 2 %',
        },
    ]
}

export const moonStats = {
    title: 'moon Stats',
    content: [
        {
            label: 'Mass',
            info: '0.0123 Earth Masses',
        },
        {
            label: 'Diameter',
            info: '3476 km',
        },
        {
            label: 'Density',
            info: '3.3 g / cm<sup>3</sup>',
        },
        {
            label: 'Surface Gravity',
            info: '0.17',
        },
        {
            label: 'Escape Velocity',
            info: '2.4 km / s',
        },
        {
            label: 'Rotation Period',
            info: '27.3 days',
        },
        {
            label: 'Surface Area',
            info: '0.7',
        },
        
    ]
}