export const stats = {
    radius: {
        title: "Diameter",
        stat: [
            "142,984 kilometers",
        ],
    },
    distanceFromSun: {
        title: "Distance from Sun",
        stat: [
            "5.20 astronomical units",
        ],
    },
    mass: {
        title: "Mass",
        stat: [
            "18,991 x 10<sup>23</sup> kg",
        ],
    },
    density: {
        title: "Density",
        stat: [
            "1.3 g / cm<sup>3</sup>",
        ],
    },
    revolution: {
        title: "Revolution Period",
        stat: [
            "11.86 years",
        ],
    }
}

export const geological = {
    // volcano: {
    //     title: 'Volcanoes',
    //     icon: 'volcano',
    //     paragraphs: ""

    // },
    // plateTec: {
    //     title: "Plate Tectonics",
    //     icon: 'house-crack',
    //     paragraphs: ''
    // },
    magnet: {
        title: "Magnetic Field",
        icon: 'magnet',
        paragraphs: "Jupiter has a strong magnetic field due to the electric current generated by the metallic hydrogen layer (<em>Giant Planets Magnetospheres</em>). Jupiter's magnetic field results in a magnetosphere similar to Earth's. Jupiter's magnetic field results in a magnetosphere significantly larger than Earth's; thus, Jupiter's magnetosphere can block solar winds further away from the planet than Earth's magnetosphere can (<em>Giant Planets Magnetospheres</em>)."
    },
}

export const comp = {
    p: "",
}

export const size = {
    p: "Jupiter is the largest planet in the solar system. If you summed the masses of the other planets in the solar system, Jupiter's mass would still exceed theirs (Franck et al).  "
}
export const structure = {
    p: "Jupiter is categorized as a Jovian planet. Jovian planets consist of a core made of rock, metal, and hydrogen compounds with the rest of the planet being composed of hydrogen and helium. Its core is around 10 Earth masses in size in order for the planet to be able to gain an envelope of gas."
}
export const surface = {
    p: "Jupiter does not have a surface. Instead, the planet’s atmosphere proceeds to get denser and denser as you move towards the center of the planet as a result of an increase in pressure. ",
    p2: "One well-known feature of Jupiter is its Red Spot, a hurricane-like storm located in the planet’s atmosphere. To demonstrate the size of the storm, it's four times the size of Earth! The Red Spot has occurred for at least 400 years, and it's unsure when it will stop. One very interesting fact about the spot is that it glows very bright when viewed in infrared light."
}

export const moons = {
    io: {
        name: "Io",
        p: "Io, one of Jupiter’s 96 moons, is the most volcanic body in the solar system. The moon is composed of rock and metal.",
        geo: "Areas that appear black, brown, green, orange, and red denote active volcanic areas (<em>High Resolution Global View of Io</em>). Even though Io is smaller than Earth, its interior is molten, and as a result, the moon has plate tectonics alongside its volcanic activity. The plate tectonics renew the moon’s surface, resulting in a crater-free smooth surface. The reason Io’s interior is molten is due to tidal heating.",
    },
    europa: {
        name: 'Europa',
        p: "Europa, another one of Jupiter’s moons, is composed of ice, rock, and metal and surrounded by a 100-kilometer-thick H<sub>2</sub>O layer. This moon is smaller than Io. On the moon’s surface is ice and more shockingly, the planet’s interior is a liquid ocean. This interior ocean is a result of the tidal heating the moon faces.",
        geo: "Similar to Io, the smooth surface of the planet is a result of tectonic activity. "
    },
}