export const stats = {
    radius: {
        title: "Diameter",
        stat: [
            "49,660 kilometers",
        ],
    },
    distanceFromSun: {
        title: "Distance from Sun",
        stat: [
            "30.06 astronomical units",
        ],
    },
    mass: {
        title: "Mass",
        stat: [
            "1030 x 10<sup>23</sup> kg",
        ],
    },
    density: {
        title: "Density",
        stat: [
            "1.6 g / cm<sup>3</sup>",
        ],
    },
    revolution: {
        title: "Revolution Period",
        stat: [
            "164.82 years",
        ],
    }
}

export const geological = {
    magnet: {
        title: "Magnetic Field",
        icon: 'magnet',
        paragraphs: "Neptune is surrounded by a weak magnetic field thought to be generated by the planet’s core (<em>Giant Planets Magnetospheres</em>). Neptune’s magnetosphere is not aligned with the planet’s axis, which results in stark variations (<em>Neptune Facts</em>)."
    },
}

export const comp = {
    p1: "Neptune’s outmost clouds are composed of methane and the white narrow clouds that appear on the planet are made of methane ice crystals(Franck et al).",
}

export const size = {
    p: "When compared to Earth, Neptune is 4 times is size (<em>Neptune Facts</em>)."
}

export const structure = {
    p: "Neptune's atmosphere reflects various frequencies of visible light, resulting in the planet's very blue color (Frank et al.). Earth's atmospheric color is a result of a similar process.",
}

export const surface = {
    p: "Like all the other gas giants, Neptune lacks a surface. Due to the increase of pressure as you move towards the planet's center, the planet’s atmosphere becomes denser and denser. The planet is c", 
}

export const moons = {
    triton: {
        name: "Triton",
        p: "Triton, one of Neptune’s 16 moons, is the only moon in the galaxy that rotates in the opposite direction of the planet (<em>Neptune Facts</em>). Some scientists think that this odd rotation may be a result of the moon being an object created then captured by Neptune’s orbit (<em>Neptune Facts</em>).",
    },
}