export const stats = {
    radius: {
        title: "Diameter",
        stat: [
            "49,660 kilometers",
        ],
    },
    distanceFromSun: {
        title: "Distance from Sun",
        stat: [
            "30.06 astronomical units",
        ],
    },
    mass: {
        title: "Mass",
        stat: [
            "1030 x 10<sup>23</sup> kg",
        ],
    },
    density: {
        title: "Density",
        stat: [
            "1.6 g / cm<sup>3</sup>",
        ],
    },
    revolution: {
        title: "Revolution Period",
        stat: [
            "164.82 years",
        ],
    }
}

export const geological = {
    // volcano: {
    //     title: 'Volcanoes',
    //     icon: 'volcano',
    //     paragraphs: ""

    // },
    // plateTec: {
    //     title: "Plate Tectonics",
    //     icon: 'house-crack',
    //     paragraphs: ''
    // },
    magnet: {
        title: "Magnetic Field",
        icon: 'magnet',
        paragraphs: "Neptune is surrounded by a weak magnetic field thought to be generated by the planet’s core [1]."
    },
}

export const comp = {
    p1: "",
}

export const size = {
    p: ""
}

export const structure = {
    p: ""
}

export const surface = {
    p: "Like all the other gas giants, Neptune lacks a surface. Due to the increase of pressure as you move towards the planet's center, the planet’s atmosphere becomes denser and denser.",
    p1: 'Neptune’s outmost clouds are composed of methane [Textbook].'
}