export const stats = {
    radius: {
        title: "Diameter",
        stat: [
            "120,536 kilometers",
        ],
    },
    distanceFromSun: {
        title: "Distance from Sun",
        stat: [
            "9.54 astronomical units",
        ],
    },
    mass: {
        title: "Mass",
        stat: [
            "5686 x 10<sup>23</sup> kg",
        ],
    },
    density: {
        title: "Density",
        stat: [
            "0.7 g / cm<sup>3</sup>",
        ],
    },
    revolution: {
        title: "Revolution Period",
        stat: [
            "29.46 years",
        ],
    }
}

export const geological = {
    // volcano: {
    //     title: 'Volcanoes',
    //     icon: 'volcano',
    //     paragraphs: ""

    // },
    // plateTec: {
    //     title: "Plate Tectonics",
    //     icon: 'house-crack',
    //     paragraphs: ''
    // },
    magnet: {
        title: "Magnetic Field",
        icon: 'magnet',
        paragraphs: "Like Jupiter, Saturn possesses a magnetic field generated by its layer of metallic hydrogen (<em>Giant Planets Magnetospheres</em>). However, Saturn's layer is smaller than that of Jupiter, resulting in a weaker and less extensive magnetosphere (<em>Giant Planets Magnetospheres</em>)."
    },
}

export const comp = {
    p1: "",
}

export const size = {
    p: "Saturn is the second largest planet in the solar system."
}

export const structure = {
    p: "Saturn is known for its rings, but they are not as unique as you might think. Every planet in our outer solar system has rings as a result of the constant release of ring particles by moonlets as they are impacted by sand-sized particles. Saturn's rings are super, super thin, and not solid. Instead, the rings are composed of chunks of ice that are around 1 meter in size and orbit the planet in a plane. "
}

export const surface = {
    p: "Saturn is another planet that does not have a surface. Instead, the planet’s atmosphere proceeds to get denser and denser as you move toward the planet's center because of increased pressure. "
}

export const moons = {
    enceladus: {
        name: "Enceladus",
        p: "Enceladus is one of Saturn’s moons and is majority composed of ice. ",
        geo: "The moon faces continuous tectonic activity resulting in ice geysers which are due to the liquid water under the moon’s surface. Enceladus’s interior is not a liquid ocean like Europa, one of Jupiter’s moons, instead the water appears in hot spots or lakes underneath the surface. The tectonic activity is also responsible for the smooth surface.",
    },

}